export const WebsocketTypes = {
  CONNECT_WEBSOCKET: 'CONNECT_WEBSOCKET',
  CONNECT_WEBSOCKET_SUCCESS: 'CONNECT_WEBSOCKET_SUCCESS',
  DISCONNECT_WEBSOCKET: 'DISCONNECT_WEBSOCKET',
  DISCONNECT_WEBSOCKET_SUCCESS: 'DISCONNECT_WEBSOCKET_SUCCESS',
  RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
  RECEIVE_MESSAGE_SUCCESS: 'RECEIVE_MESSAGE_SUCCESS',
  ACTIVITY_SOCKET_LOADING: 'ACTIVITY_SOCKET_LOADING',
  ACTIVITY_SOCKET_LOADFAILED: 'ACTIVITY_SOCKET_LOADFAILED',
  RECEIVE_EXCEPTION: 'RECEIVE_EXCEPTION',
  CLEAR_EXCEPTION: 'CLEAR_EXCEPTION'
}